#!/usr/bin/env python3
"""
TeslaUSB Configuration Wrapper

This file loads configuration from config.yaml using PyYAML.
DO NOT EDIT THIS FILE - edit config.yaml instead.

This wrapper provides Python variables from YAML for the web application.
"""

import os
import secrets
import yaml

# Determine config.yaml location (two levels up from web/)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_YAML = os.path.join(os.path.dirname(os.path.dirname(SCRIPT_DIR)), 'config.yaml')

# Verify config.yaml exists
if not os.path.exists(CONFIG_YAML):
    raise FileNotFoundError(f"Configuration file not found at {CONFIG_YAML}")

# Load configuration from YAML
with open(CONFIG_YAML, 'r') as f:
    config = yaml.safe_load(f)

# ============================================================================
# Extract configuration values from YAML
# ============================================================================

# Installation & Paths
# Auto-derive GADGET_DIR from this file's location (run-in-place)
# This ensures the correct path regardless of username or install location.
# scripts/web/config.py -> two levels up is the gadget directory
GADGET_DIR = os.path.dirname(os.path.dirname(SCRIPT_DIR))
TARGET_USER = config['installation']['target_user']
MNT_DIR = config['installation']['mount_dir']

# Disk Images
IMG_CAM_NAME = config['disk_images']['cam_name']
IMG_LIGHTSHOW_NAME = config['disk_images']['lightshow_name']
IMG_MUSIC_NAME = config['disk_images'].get('music_name', 'usb_music.img')
MUSIC_ENABLED = bool(config['disk_images'].get('music_enabled', False))
MUSIC_FS = config['disk_images'].get('music_fs', 'fat32')
MUSIC_LABEL = config['disk_images'].get('music_label', 'Music')

# Computed image file paths (used for feature-availability checks)
IMG_CAM_PATH = os.path.join(GADGET_DIR, IMG_CAM_NAME)
IMG_LIGHTSHOW_PATH = os.path.join(GADGET_DIR, IMG_LIGHTSHOW_NAME)
IMG_MUSIC_PATH = os.path.join(GADGET_DIR, IMG_MUSIC_NAME)

# Network & Security
WEB_PORT = config['network']['web_port']

# Web Application Configuration
_DEFAULT_SECRET = 'CHANGE-THIS-TO-A-RANDOM-SECRET-KEY-ON-FIRST-INSTALL'
SECRET_KEY = config['web']['secret_key']

# Auto-generate a secret key on first run if still using default
if SECRET_KEY == _DEFAULT_SECRET:
    SECRET_KEY = secrets.token_hex(32)
    print(f"Generated new SECRET_KEY. Consider saving it to config.yaml for persistence.")

# Lock Chime Configuration
LOCK_CHIME_FILENAME = config['web']['lock_chime_filename']
CHIMES_FOLDER = config['web']['chimes_folder']
MAX_LOCK_CHIME_SIZE = config['web']['max_lock_chime_size']
MAX_LOCK_CHIME_DURATION = config['web']['max_lock_chime_duration']
MIN_LOCK_CHIME_DURATION = config['web']['min_lock_chime_duration']

# Audio Trimmer Configuration
SPEED_RANGE_MIN = config['web']['speed_range_min']
SPEED_RANGE_MAX = config['web']['speed_range_max']
SPEED_STEP = config['web']['speed_step']

# Light Show Configuration
LIGHT_SHOW_FOLDER = config['web']['lightshow_folder']
MAX_UPLOAD_SIZE_MB = int(config['web'].get('max_upload_size_mb', 2048))
MAX_UPLOAD_CHUNK_MB = int(config['web'].get('max_upload_chunk_mb', 16))
USE_METRIC = config['web'].get('units', 'imperial').lower() == 'metric'

# Mapping & Geo-Indexing Configuration
_mapping = config.get('mapping', {})
MAPPING_ENABLED = bool(_mapping.get('enabled', False))
MAPPING_INDEX_ON_STARTUP = bool(_mapping.get('index_on_startup', True))
MAPPING_INDEX_ON_MODE_SWITCH = bool(_mapping.get('index_on_mode_switch', True))
MAPPING_SAMPLE_RATE = int(_mapping.get('sample_rate', 30))
MAPPING_TRIP_GAP_MINUTES = int(_mapping.get('trip_gap_minutes', 5))
MAPPING_ARCHIVE_INDEXING = bool(_mapping.get('archive_indexing', True))
MAPPING_DB_PATH = os.path.join(GADGET_DIR, 'geodata.db')
_event_cfg = _mapping.get('event_detection', {})
MAPPING_EVENT_THRESHOLDS = {
    'harsh_brake_threshold': float(_event_cfg.get('harsh_brake_threshold', -4.0)),
    'emergency_brake_threshold': float(_event_cfg.get('emergency_brake_threshold', -7.0)),
    'hard_accel_threshold': float(_event_cfg.get('hard_accel_threshold', 3.5)),
    'sharp_turn_lateral_g': float(_event_cfg.get('sharp_turn_lateral_g', 4.0)),
    'speed_limit_mps': float(_event_cfg.get('speed_limit_mps', 35.76)),
    'fsd_disengage_detect': bool(_event_cfg.get('fsd_disengage_detect', True)),
}

# Cloud Archive Configuration
_cloud = config.get('cloud_archive', {})
CLOUD_ARCHIVE_ENABLED = bool(_cloud.get('enabled', False))
CLOUD_ARCHIVE_SYNC_ENABLED = bool(_cloud.get('sync_enabled', True))  # auto-sync on/off (separate from page access)
CLOUD_ARCHIVE_PROVIDER = _cloud.get('provider', '')
CLOUD_ARCHIVE_REMOTE_PATH = _cloud.get('remote_path', 'TeslaUSB')
CLOUD_ARCHIVE_SYNC_FOLDERS = _cloud.get('sync_folders', ['SentryClips', 'SavedClips'])
CLOUD_ARCHIVE_PRIORITY_ORDER = _cloud.get('priority_order', ['SentryClips', 'SavedClips'])
CLOUD_ARCHIVE_MAX_UPLOAD_MBPS = int(_cloud.get('max_upload_mbps', 5))
CLOUD_ARCHIVE_RESERVE_GB = float(_cloud.get('cloud_reserve_gb', 1))
CLOUD_ARCHIVE_SYNC_NON_EVENT = bool(_cloud.get('sync_non_event_videos', False))
CLOUD_AUTO_CLEANUP = bool(_cloud.get('cloud_auto_cleanup', False))
CLOUD_CLEANUP_THRESHOLD_PCT = int(_cloud.get('cloud_cleanup_threshold_pct', 90))
CLOUD_MIN_RETENTION_DAYS = int(_cloud.get('cloud_min_retention_days', 30))
CLOUD_ARCHIVE_DB_PATH = os.path.join(GADGET_DIR, 'cloud_sync.db')
CLOUD_PROVIDER_CREDS_PATH = os.path.join(GADGET_DIR, 'cloud_provider.enc')

# Live Event Sync Configuration
# Separate first-class subsystem from cloud_archive — own queue, worker, and config.
# Shares CLOUD_ARCHIVE_PROVIDER + CLOUD_PROVIDER_CREDS_PATH for credentials only.
_les = config.get('live_event_sync', {})
LIVE_EVENT_SYNC_ENABLED = bool(_les.get('enabled', False))
LIVE_EVENT_WATCH_FOLDERS = list(_les.get('watch_folders', ['SentryClips', 'SavedClips']))
LIVE_EVENT_UPLOAD_SCOPE = str(_les.get('upload_scope', 'event_minute'))
LIVE_EVENT_RETRY_MAX_ATTEMPTS = int(_les.get('retry_max_attempts', 5))
LIVE_EVENT_RETRY_BACKOFF_SECONDS = list(_les.get('retry_backoff_seconds', [30, 120, 300, 900, 3600]))
LIVE_EVENT_DAILY_DATA_CAP_MB = int(_les.get('daily_data_cap_mb', 0))
LIVE_EVENT_NOTIFY_WEBHOOK_URL = str(_les.get('notify_webhook_url', '') or '')

# RecentClips Archive Configuration
_archive = config.get('archive', {})
ARCHIVE_ENABLED = bool(_archive.get('enabled', True))
ARCHIVE_INTERVAL_MINUTES = int(_archive.get('interval_minutes', 5))
ARCHIVE_RETENTION_DAYS = int(_archive.get('retention_days', 30))
ARCHIVE_MIN_FREE_SPACE_GB = int(_archive.get('min_free_space_gb', 10))
ARCHIVE_MAX_SIZE_GB = int(_archive.get('max_size_gb', 50))
ARCHIVE_ONLY_DRIVING = bool(_archive.get('only_driving', True))
_archive_path = _archive.get('path', '')
ARCHIVE_DIR = _archive_path if _archive_path else os.path.join(
    os.path.expanduser(f"~{TARGET_USER}"), 'ArchivedClips'
)

# ============================================================================
# ADVANCED SETTINGS - Computed values (don't modify these)
# ============================================================================

# Read-only mount directory for present mode (computed from MNT_DIR)
RO_MNT_DIR = MNT_DIR  # Same as MNT_DIR since we use -ro and -rw suffixes

# State management
STATE_FILE = os.path.join(GADGET_DIR, "state.txt")

# USB drive configuration
USB_PARTITIONS = tuple(
    part for part in ("part1", "part2", "part3")
    if part != "part3" or MUSIC_ENABLED
)

PART_LABEL_MAP = {
    "part1": "gadget_part1",
    "part2": "gadget_part2",
    **({"part3": "gadget_part3"} if MUSIC_ENABLED else {}),
}

# Mode display configuration
MODE_DISPLAY = {
    "present": ("USB Gadget Mode", "present"),
    "edit": ("Edit Mode", "edit"),
    "unknown": ("Unknown", "unknown"),
}

# File type configurations
VIDEO_EXTENSIONS = ('.mp4', '.avi', '.mov', '.mkv')
LIGHT_SHOW_EXTENSIONS = ('.fseq', '.mp3', '.wav')

# Tesla camera angles (6 cameras)
CAMERA_ANGLES = ('front', 'back', 'left_repeater', 'right_repeater', 'left_pillar', 'right_pillar')


def empty_camera_videos():
    """Return a new dict of camera angles with None values (no video assigned)."""
    return {cam: None for cam in CAMERA_ANGLES}


def empty_encrypted_flags():
    """Return a new dict of camera angles with False values (not encrypted)."""
    return {cam: False for cam in CAMERA_ANGLES}


# Script paths (scripts are in GADGET_DIR/scripts/)
def get_script_path(script_name):
    """Get the full path to a script in the GADGET_DIR/scripts/ directory."""
    return os.path.join(GADGET_DIR, "scripts", script_name)
